# Generated by Django 4.2 on 2024-06-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('category', models.IntegerField(choices=[(1, '宠物食品'), (2, '宠物药品'), (3, '宠物玩具')], verbose_name='商品分类')),
                ('title', models.CharField(max_length=255, verbose_name='商品标题')),
                ('image_url', models.ImageField(blank=True, max_length=200, null=True, upload_to='image/shop', verbose_name='商品封面url')),
                ('text', models.TextField(verbose_name='商品介绍')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价')),
                ('sold_num', models.PositiveIntegerField(default=0, verbose_name='销量')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('favor_count', models.PositiveIntegerField(default=0, verbose_name='赞数')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'goods_info',
            },
        ),
        migrations.CreateModel(
            name='GoodsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.goodsinfo', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '商品评论',
                'verbose_name_plural': '商品评论',
                'db_table': 'goods_comment',
            },
        ),
    ]
