# Generated by Django 4.2 on 2024-06-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('token', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='TOKEN')),
                ('user_email', models.EmailField(max_length=64, verbose_name='邮箱')),
                ('category', models.IntegerField(choices=[(1, '普通用户'), (2, '宠物医生')], verbose_name='分类')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_image_url', models.ImageField(blank=True, max_length=200, null=True, upload_to='image/doctors', verbose_name='职业证书照片')),
                ('certificate_number', models.CharField(max_length=32, unique=True, verbose_name='执业证书编号')),
                ('real_name', models.CharField(max_length=32, verbose_name='真实姓名')),
                ('ID_number', models.CharField(max_length=32, verbose_name='身份证号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo', verbose_name='医生用户')),
            ],
            options={
                'verbose_name': '医生额外信息',
                'verbose_name_plural': '医生额外信息',
                'db_table': 'doctor_info',
            },
        ),
    ]
