# Generated by Django 4.2.13 on 2024-06-09 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='ID_number',
            field=models.CharField(help_text='身份证号', max_length=32, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='certificate_image_url',
            field=models.ImageField(blank=True, help_text='职业证书照片', max_length=200, null=True, upload_to='image/doctors', verbose_name='职业证书照片'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='certificate_number',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='执业证书编号'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='real_name',
            field=models.CharField(help_text='真实姓名', max_length=32, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='user',
            field=models.ForeignKey(help_text='医生用户', on_delete=django.db.models.deletion.CASCADE, to='users.userinfo', verbose_name='医生用户'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='category',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, '宠物医生')], help_text='用户分类', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(help_text='密码', max_length=128, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='token',
            field=models.CharField(blank=True, db_index=True, help_text='用户登录token', max_length=64, null=True, verbose_name='TOKEN'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_email',
            field=models.EmailField(help_text='邮箱', max_length=64, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(db_index=True, help_text='用户名', max_length=32, verbose_name='用户名'),
        ),
    ]
